travis:
  secure:
    BINSTAR_TOKEN: gtKgovocJVPVHCH7MdKJJVvQhnMdnN3c1XXwmVqZCe0UVdGFL64n2YYprYdRliacXNtsdhYVWiBl4mU/q3HOiRCLDS7lysM43DnT46J6FnDaB8QrKcP00P/f8tsQoed6evnmbu6q+gmNMtVIrqW5ID+NL2Sdk84dne6HwT8okQjLSIM9RDwfz23tXkcO9qJD+D5/1UIBj5asBw91dTWlerrHCxXsSImU3cCobzvNpB/PJTpy4UWEFltPjgHwWRAHVCzcFw2PQblkBrwRN0zQTD5kvN1gWYhZFlJDyB/s4VQma7+lRWNxkF+fHljUOD/9zbOt5wxhpx4psEf5/GAAmkxRJMTHDZNvSOs/ntedgjx+8NZ7jRtXCP2KJUaEhH+uIhtw73aW9dNEjzi15mBnN6Hsx+QS2XgE1wFkGuCOhH6CtxViVXZjkzN5+XlEBNXHpIf3RYZVEo4JBmATK/oygUIfhxPjOcWSaOoC4JO5F5yHKHTHrUsPvIqArwqiyDQUAQWrA6TzHe1+4/4F1VO+zl72BMdoea5m6b5IAbxvqgfTFpXgMrP4e2VDQpDUS5hVoZAlf7OdfOkMVcB6feBNXfOk2fJwPJ/Y7rM1fff4UnxAWwoZ/C2s+0u1OdJnGhqLoaYaAw3PnfW9y1U5TDKghtDU2RYLrYpGGs3msTnVI/4=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
