travis:
  secure:
    BINSTAR_TOKEN: seyLDj07PkUGKEkaPFR1MxBGzjC+5gCT3N87vFgYpUbOO46orLw8T4pfS7phXb7ZMyFdMFhJcazkk7DI8nj3MR9NZBB3X3i6p5HF83DoKqIRQOKehRO5ORxAb3uVkHYmOBCqFdPw0cpFfngYF/CAxnz6J1jFAUxkEs9Z7F+e5D+c3onQ28vnTe9JoofMRYApeedfojqjAwytfRrOqHKXk+SVQPJ9JapQvAE8CdSRGyA8+9LLdBKWRaMii7U+3eUHDwimmCMab6LMygdGniu0H4BgsoK6MYxSr7mbBnfFDe2dHUrvamQ/j4J9kyoQTvOwX1v06MZwxon8OxFwJQDWhfGeQbxkAXU6Wm1pAHojnt2xt8q6vb9BHiXIOsCDAPwI1LC3cn/cdE3cGFg8qWdCpFQAXhAOy2pb/xyRnMPiCxZsw676llzKC2XicR0wwWyvuM0nc+K/pabQaSA3tzWxohGzQzmI9kNIagrYpSr0jmZSa1HlbFiRSjRwBRWHjlZZkzdGdXxeAl9+m8Q9HWXCMBvU1m0SZ9yrz5LXQSx1pzKTda8zH4iIqD7AVS1BQ8xhChUnZaVG+5qq0Pck6zju4JyDgl29Al9IKHuXRM5Du1faammgZqR+7lpfYjoztA9udIqLfH/gSQyj02W90vvILqqrxOlp9CqqPaDjFKFiwDg=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
