travis:
  secure:
    BINSTAR_TOKEN: G0xLyRf+N7w3CXC9XWyOrnvIqhr2cdZeomBFNWD4QAkBGYAPF5rTowpkaBZbDyprAY0+s7W8NmNRkiLMg9vXPVngtgfUrIaK/GMQHJLFjGcsNKhCRJhAMk0x/yb1wYuvUlHUaaBqneHMlr0Kn0nSqLZOO1IqDZcf0W89OLI3oNRkHsXoEXX33+BcMHLyZlG/pSVuBhIzivA98n5d13CbobJ/VBrV4PBF9Q076/PFGaULBItw9UfjGT1UOZmpWW654/Fqiv8j+D48hmZmm7VGxblKOa+cIfJNlag7pXKBFPd2Le/iaDYSn7dDjJyjyeH9suwHWLfYP8b7AtwVbUR5rXuGitO4upjhRzFrddqmqd0EhDIHWg5tSgjC9yiFba6zQDT6BOExp/vyBGa8LePAK3+8X7/fSW0++zv48ZdAYh4MneBuzud+Z7rsxwdmo4ljCN6poZ1rMrK54x8T2Fd8CMSdfxknu7N6cdh8Ds8eSM3u4i0U0EV+lghlEOm0gpghdvS67aFVQPPRkVxbt4I5iw06jdxgueCVCf2Lvlpmr29+XzUt4NfL48ndHn09AuAbWNW817vIU46d9KDeJzpnix156AmQenHp1IEsS4IDuUZ1seBfa0pVQnWKXOFF05nL8bFYay13LnK5Kg2lGnEsWP9pPGLwmmv6eGiev+OOcHs=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
